name: ci

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.node }}

      - name: Install dependencies
        run: bun install

      - name: Run typecheck
        run: bun run typecheck

      - name: Run lint
        run: bun run lint
